[settings]
name = "ATBA"
loadout_file = ""
root_dir = ""
run_command = "ATBA.exe"
run_command_linux = "./ATBA"
agent_id = "RLBotCPP/ATBA"
hivemind = true

[details]
description = "Made possible by RLBot"
fun_fact = "This is a test bot"
source_link = "https://github.com/mtheall/RLBotCPP"
developer = "BotMaker"
language = "C++"
tags = []
